steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "github.com/Tyson-Mike/spinnaker-test"]
    env: ["PROJECT_ROOT=github.com/Tyson-Mike/spinnaker-test"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/tyson-lab-containers/gcp-cd-codelab:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "gcr.io/tyson-lab-containers/gcp-cd-codelab:$REVISION_ID"
